### ISSUE TITLE
Lavarel 4.2

### ISSUE THREAD

**Issue by ChristopherDosin** [Maghrooni/googlemap#1]
Hello,

is it possible to install your api on Lavarel 4.2 via Composer ?
If so - how ?

**Comment by Maghrooni** [comment]
Hi , 
unfortunately I won't maintain this code , as the main idea of having javascript code echo'ed by PHP is not a good and right way to use google maps API.
reason of this bundle was to help show google map as simple as possible on laravel 3.x applications.
and answer to your question is no, it is a bundle (available for laravel 3.x only) and depends highly on config files for the bundle.
and in summary I don't recommend using it ! you can simply use the google map's APIs [here](https://developers.google.com/maps/web/).
